server:
  port: 9092

hystrix: 
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000
            
jwt: 
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400 

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource: 
    url: jdbc:postgresql://postgres:5432/csds
    username: root
    password: P@ssword21
    
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
              allowedOrigins: "*"
              allowedMethods: "*"
              allowedHeaders: "*"
#      routes:
#        - id: AuthService
#          uri: lb://CORE-SERVICE
#          predicates:
#          - Path=/auth/**